import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const { icons } = JSON.parse(
    readFileSync(
        require.resolve("@esri/calcite-ui-icons/docs/icons.json"),
        "utf8",
    ),
);
// The Survey123 sprite approach, limited to this app's icons to keep startup small.
const names = [
    "arrow-left",
    "arrow-right",
    "caret-left",
    "caret-right",
    "chevron-left",
    "chevron-right",
    "chevron-start",
    "chevron-end",
    "chevrons-left",
    "chevrons-right",
    "brightness",
    "moon",
    "desktop",
    "dashboard",
    "folders",
    "folder",
    "folder-open",
    "code-branch",
    "console",
    "gear",
    "file-code",
    "file-text",
    "file",
    "search",
    "plus",
    "refresh",
    "save",
    "download",
    "upload",
    "launch",
    "check",
    "check-circle",
    "check-circle-f",
    "exclamation-mark-triangle",
    "information",
    "x-circle",
    "x",
    "lock",
    "spinner",
    "ellipsis",
    "copy",
    "play",
    "clock",
    "list",
    "link",
];
const directory = new URL("../src/lib/generated/", import.meta.url);
mkdirSync(directory, { recursive: true });
const symbols = names.flatMap((name) =>
    [16, 24, 32].map((size) => {
        if (!icons[name]) throw new Error(`Unknown Calcite icon: ${name}`);
        const layers =
            typeof icons[name][size] === "string"
                ? [{ d: icons[name][size] }]
                : icons[name][size];
        return `<symbol id="icon-${name}-${size}" viewBox="0 0 ${size} ${size}">${layers.map(({ d, opacity }) => `<path d="${d}"${opacity ? ` opacity="${opacity}"` : ""}/>`).join("")}</symbol>`;
    }),
);
writeFileSync(
    new URL("calcite-icons.svg", directory),
    `<svg xmlns="http://www.w3.org/2000/svg" id="calcite-icon-sprite" aria-hidden="true" style="position:absolute;width:0;height:0;overflow:hidden">${symbols.join("")}</svg>`,
);
writeFileSync(
    new URL("icon-names.ts", directory),
    `// Generated by scripts/generate-icons.js.\nexport type IconName = ${names.map((name) => JSON.stringify(name)).join(" | ")};\n`,
);
